# Generated by Django 5.2.11 on 2026-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='query_voice/'),
        ),
    ]
