# Generated by Django 5.2.11 on 2026-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_query_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='query_images/'),
        ),
    ]
