# Generated by Django 5.2.11 on 2026-02-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_query_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='query',
            name='media_file',
        ),
        migrations.AddField(
            model_name='query',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='responses/'),
        ),
        migrations.AddField(
            model_name='query',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_voice', models.FileField(blank=True, null=True, upload_to='expert_voice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query')),
            ],
        ),
    ]
