# Generated by Django 5.2.11 on 2026-03-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_article'),
        ('core', '0005_notification'),
    ]

    operations = [
    ]
