# Generated by Django 5.2.11 on 2026-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_diseasedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetection',
            name='crop',
            field=models.CharField(default='tomato', max_length=50),
            preserve_default=False,
        ),
    ]
