# Generated by Django 6.0.4 on 2026-04-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_userprofile_crop_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='land_unit',
            field=models.CharField(choices=[('acre', 'Acre'), ('hectare', 'Hectare')], default='acre', max_length=20),
        ),
    ]
