# Generated by Django 6.0.4 on 2026-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_land_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('soil_image', models.ImageField(upload_to='soil_images/')),
                ('ph', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('organic_carbon', models.FloatField()),
                ('moisture', models.CharField(max_length=50)),
                ('soil_health', models.CharField(blank=True, max_length=200)),
                ('recommended_crop', models.CharField(blank=True, max_length=200)),
                ('fertilizer', models.CharField(blank=True, max_length=200)),
                ('irrigation', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SoilAnalysis',
        ),
    ]
